### ISSUE TITLE
Unable to determine webpage signup location

### ISSUE THREAD

**Issue by AntonERG** [proteusthemes/mailchimp-widget#2]
Dear Support,

I'd like to determine webpage signup location, one of the solutions from mailchimp is listed here:
https://mailchimp.com/help/determine-webpage-signup-location/

I've purchased your theme GymPress PT, where your mailchimp plugin was already integrated.

How can I track which subscription form and from which page my customers use?

**Comment by capuderg** [comment]
Hi,

our mailchimp widget is meant for basic email collection. If you want to use a more advanced forms, you should embed a custom mailchimp form to your site with a HTML widget. This way you will be able to add fields that you want and track exactly what you want.

Take care!
